name: Quarto Publish

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    permissions:
      contents: write  # Allow write access to repository contents

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages  # Publish to the gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
